name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: h76.seohost.pl
          username: srv105070
          port: 57185
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd public_html/wp-content/themes/sunnycode
            git pull